apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-server
  template:
    metadata:
      labels:
        app: react-server
    spec:
      containers:
        - name: react-server
          image: naveendra/react-blog:latest
          resources:
            requests:
              memory: "256Mi"   # Memory request for the container
              cpu: "0.5"         # CPU request for the container (0.5 CPU cores)
            limits:
              memory: "512Mi"   # Memory limit for the container
              cpu: "1"           # CPU limit for the container (1 CPU core)
          ports:
            - containerPort: 80